--------------------------------------------------------
--  File created - Thursday-April-19-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_PERSONA
--------------------------------------------------------

  CREATE TABLE "TEST_CONECCION"."TBL_PERSONA" 
   (	"ID_PERSONA" NUMBER(*,0), 
	"P_NOMBRE" VARCHAR2(100 BYTE), 
	"P_APELLIDO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TEST_CONECCION.TBL_PERSONA
SET DEFINE OFF;
Insert into TEST_CONECCION.TBL_PERSONA (ID_PERSONA,P_NOMBRE,P_APELLIDO) values (1,'WILIAN','BARAHONA');
Insert into TEST_CONECCION.TBL_PERSONA (ID_PERSONA,P_NOMBRE,P_APELLIDO) values (2,'PEDRO','BARAHONA');
Insert into TEST_CONECCION.TBL_PERSONA (ID_PERSONA,P_NOMBRE,P_APELLIDO) values (3,'JUAN','BARAHONA');
Insert into TEST_CONECCION.TBL_PERSONA (ID_PERSONA,P_NOMBRE,P_APELLIDO) values (4,'PABLO','MONCADA');
--------------------------------------------------------
--  Constraints for Table TBL_PERSONA
--------------------------------------------------------

  ALTER TABLE "TEST_CONECCION"."TBL_PERSONA" ADD PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
